language: go

go:
  - tip

cache:
  directories:
  - $HOME/protobuf

sudo: false

before_install:
  - ./install-protobuf.sh
  - export PATH=$PATH:$HOME/protobuf/bin/
  - go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

install:
  - ./build.sh
